name: Prettier Format
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # No install step needed
      - name: Run Prettier (bunx)
        run: bunx -y prettier --write .

      - name: Commit changes
        run: |
          git config --global user.name "ColdranTest"
          git config --global user.email "internet3.sh@gmail.com"
          git add -A
          git diff --staged --quiet || git commit -m "chore: format with Prettier"

      - name: Push
        run: git push
